create database Task1;
use Task1;
create table supermarket(no_of_stocks int,name_of_products char(50));
desc supermarket;
insert into supermarket values(100,'Juices');
select * from supermarket;
insert into supermarket values(1000,'biscuits');
insert into supermarket values(1050,'corn');
insert into supermarket values(1200,'chips');
insert into supermarket values(300,'wafer');
insert into supermarket values(500,'champor');
select * from supermarket where no_of_stocks=500;
select * from supermarket where no_of_stocks>500;
select * from supermarket where no_of_stocks<500;
select * from supermarket where no_of_stocks>100 AND name_of_products='juices';
select * from supermarket where no_of_stocks>1200 AND name_of_products='juices';
select * from supermarket where no_of_stocks>100 or name_of_products='juices';
select * from supermarket where no_of_stocks>10000 AND name_of_products='juices';
select * from supermarket where no_of_stocks IN (1000,1500);
select * from supermarket where no_of_stocks NOT IN (1000,1500);
select * from supermarket limit 3;
select * from supermarket where no_of_stocks between 500 And 1200 limit 3;
select * from supermaket where name_of_products like 'c%';
select * from supermaket where name_of_products not like 'c%';
select * from supermaket where name_of_products like 'c%i';
select * from supermaket where name_of_products like '%i%';